### PR TITLE
Implemented toggling of image loading

### PR DESCRIPTION
**Pull request by andrew-s**

### CODE REVIEW

**Comment by gsouf** [comment]
Thanks for your contribution. Could you rename the option to "enableImages" and also I just added a section in the readme to list broswerFactory's options (https://github.com/gsouf/headless-chromium-php/blob/master/README.md#browser-factory) can you add this option here?

**Comment by gsouf** [comment]
@andrew-s Can you also document the new option here: https://github.com/gsouf/headless-chromium-php/blob/master/src/BrowserFactory.php#L29

**Comment by andrew-s** [comment]
That should be everything updated

**Comment by blackandred** [comment]
Any progress on this PR?

**Comment by gsouf** [comment]
Woops, my bad

**Pull request merged**
